name: Destroy Infrastructure

on:
  workflow_dispatch:  # Manual trigger required

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Initialize Terraform
        working-directory: ./Terraform  # Ensure this is correct
        run: terraform init -input=false

      - name: Refresh Terraform State
        working-directory: ./Terraform
        run: terraform refresh

      - name: Show Terraform State
        working-directory: ./Terraform
        run: terraform state list

      - name: Terraform Destroy (Approval Required)
        working-directory: ./Terraform
        run: |
          echo "⚠️ About to destroy all resources!"
          echo "🛑 You must manually approve this action in GitHub UI."
          sleep 10
          terraform destroy -auto-approve
