name: Provision Infrastructure

on:
  push:
    branches:
      - main  # Runs on every commit to main

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        run: |
          cd Terraform
          terraform init
          terraform apply -auto-approve

      - name: Save Bastion Host IP
        run: |

         set -e  # Exit immediately if a command fails
         
         # Check if Terraform directory exists

         if [ ! -d "Terraform" ]; then
         echo "Error: Terraform directory not found!"
         exit 1
         fi

         cd Terraform

         # Debug: Check Terraform files exist
         ls -la

         # Initialize  Terraform outputs
          terraform init -no-color || { echo "Terraform init failed!"; exit 1; } 
          
          # Refresh Terraform state (ensure outputs are up-to-date)

          terraform refresh -no-color || { echo "Terraform refresh failed!"; exit 1; }
          

          # Retrieve Bastion Host IP
         #BASTION_IP=$(terraform output -raw bastion_host 2>/dev/null || echo "")
         BASTION_IP=$(terraform output -raw bastion_host 2>/dev/null | tail -n 1 | tr -d '\r')
                  if [[ -z "$BASTION_IP" ]]; then
         echo "Error: Failed to retrieve Bastion Host IP"
         exit 1
         fi

         # Save to GitHub environment 
         echo "BASTION_IP=$BASTION_IP" >> $GITHUB_ENV
         echo "Bastion Host IP: $BASTION_IP"

      
    
 
 