name: Provision Infrastructure

on:
  push:
    branches:
      - main  # Runs on every commit to main

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        run: |
          cd Terraform
          terraform init
          terraform apply -auto-approve

      - name: Save Bastion Host IP
        run: |
          cd Terraform    
            terraform init -no-color
            terraform refresh -no-color  # Ensure outputs are up-to-date

          BASTION_IP=$(terraform output -json bastion_host | jq -r '.' 2>/dev/null || echo "FAILED")
          if [[ "$BASTION_IP" == "FAILED" || -z "$BASTION_IP" ]]; then
           echo "Error: Failed to retrieve Bastion Host IP"
           exit 1
          fi
          echo "BASTION_IP=$BASTION_IP" >> $GITHUB_ENV

       

    
